### ISSUE TITLE
When import a model with animation, other items lost texture and get a green/white/black texture

### ISSUE THREAD

**Issue by cesarminecraft** [Godlander/objmc#59] opened 2024-03-07 09:47 UTC
![imagen_2024-03-07_104640370](https://github.com/Godlander/objmc/assets/45963715/87cb236d-9993-4a14-84da-437856ee5974)

**Comment by Godlander** [comment] 2024-03-07 19:12
what is the game version? and please provide hardware information.

f3 should show most of the important info

**Comment by cesarminecraft** [comment] 2024-03-11 08:09
game version 1.20.1
![image](https://github.com/Godlander/objmc/assets/45963715/609314d2-7da0-4e39-80b5-02db3d017f49)

**Comment by Godlander** [comment] 2024-03-12 03:57
looks like its modded, try vanilla

**Comment by cesarminecraft** [comment] 2024-03-18 10:36
![image](https://github.com/Godlander/objmc/assets/45963715/d790c383-129a-4dd3-a3ab-b72736d8611e)
![image](https://github.com/Godlander/objmc/assets/45963715/c6ab35e9-8e1c-4414-9d6f-36ed9111a277)
still not working

**Comment by Godlander** [comment] 2024-04-25 23:22
narrowed it down to the entity cutout shader being the likely suspect, but still not sure exactly what causes this issue for some users
i'm unable to reproduce on my machines

**Comment by Godlander** [comment] 2024-05-26 23:36
fixed by https://github.com/Godlander/objmc/commit/940ed38dd0ca87739aa7fadd7ff5924aaf4227de

**Closed by Godlander** 2024-05-26 23:36 UTC
Labels: bug, help wanted
